#
# Note: Tests can be run locally with
#   gitlab-runner exec <executor, eg. docker> <job name>
#

cache:
  paths:
    - build

stages:
  - publish
  - docs
  - test

test-run-from-tag:
  stage:
    test
  only:
    - tags
  script:
    echo "Hello Ugur"
  when: manual

## ============================================================================
## Common settings for building docker images
## ============================================================================

#.push_docker:
#  dependencies: []
#  variables:
#    DOCKER_REGISTRY_HOST: $DOCKER_REGISTRY_HOST
#    DOCKER_REGISTRY_USER: $CI_PROJECT_NAME
#    GIT_VERSION: ${CI_COMMIT_SHA:0:8}
#  tags:
#    - docker
#    - engageska
#  image: docker:stable
#  services:
#    - docker:dind
#  before_script:
#    - apk add make git
#    - docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_HOST
#  script:
#    - cd $BUILD_PATH
#    - make DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST DOCKER_REGISTRY_USER=$CI_PROJECT_NAME pull_default
#    - make DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST DOCKER_REGISTRY_USER=$CI_PROJECT_NAME push_version
#  retry: 2


# ============================================================================
# Build documentation
# ============================================================================
#build_docs:
#  stage: test
#  image: nexus.engageska-portugal.pt/sdp-prototype/pytango_ska_dev:latest
#  before_script:
#    - pip install -r docs/requirements.txt
#  script:
#    - make -C docs html
#  artifacts:
#    paths: [docs/build/html/]
#    expire_in: 1 day
#
# variables:
#   CHARTS_TO_PUBLISH: tea

include:
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/helm_publish.yml'

  # Create Gitlab CI badges from CI metrics
  # https://developer.skatelescope.org/en/latest/tools/continuousintegration.html#automated-collection-of-ci-health-metrics-as-part-of-the-ci-pipeline
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/post_step.yml'
